name: Minio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Minio | Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Minio | Checkout
      uses: actions/checkout@v2

    - name: Minio | .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Minio | Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=coverage/ /p:CoverletOutputFormat=lcov

    - name: Minio | Tests | Coverage | Publish
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: tests/coverage/coverage.info

